import type { Metadata } from "next";
import { Geist, Geist_Mono, Exo } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar/Navbar";
import { Toaster } from "sonner";
import MySessionProvider from "../providers/MySessionProvider";
import Footer from "../components/Footer/Footer";
import ReduxProvider from "../providers/ReduxProvider";
import AppInitializer from "@/providers/AppInitializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const exo = Exo({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});

export const metadata: Metadata = {
  title: "FreshCart",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${exo.className} ${geistSans.variable}  ${geistMono.variable} antialiased`}
      >
        <MySessionProvider>
          <ReduxProvider>
            <AppInitializer>
              <Toaster />
              <Navbar />
              {children}
              <Footer />
            </AppInitializer>
          </ReduxProvider>
        </MySessionProvider>
      </body>
    </html>
  );
}
