export const egyptGovernorates = [
  { value: "cairo", label: "Cairo" },
  { value: "alexandria", label: "Alexandria" },
  { value: "giza", label: "Giza" },
  { value: "qalyubia", label: "Qalyubia" },
  { value: "port-said", label: "Port Said" },
  { value: "suez", label: "Suez" },
  { value: "ismailia", label: "Ismailia" },
  { value: "damietta", label: "Damietta" },
  { value: "dakahlia", label: "Dakahlia" },
  { value: "sharqia", label: "Sharqia" },
  { value: "gharbia", label: "Gharbia" },
  { value: "monufia", label: "Monufia" },
  { value: "kafr-el-sheikh", label: "Kafr El Sheikh" },
  { value: "beheira", label: "Beheira" },
  { value: "faiyum", label: "Faiyum" },
  { value: "beni-suef", label: "Beni Suef" },
  { value: "minya", label: "Minya" },
  { value: "asyut", label: "Asyut" },
  { value: "sohag", label: "Sohag" },
  { value: "qena", label: "Qena" },
  { value: "luxor", label: "Luxor" },
  { value: "aswan", label: "Aswan" },
  { value: "red-sea", label: "Red Sea" },
  { value: "new-valley", label: "New Valley" },
  { value: "north-sinai", label: "North Sinai" },
  { value: "south-sinai", label: "South Sinai" },
];